-- Datos iniciales para la tabla CITAS
-- Al menos 3 registros requeridos por las instrucciones

INSERT INTO CITAS (ID, NOMBRE_MASCOTA, TIPO_MASCOTA, NOMBRE_DUENO, TELEFONO_DUENO, SERVICIO, VETERINARIO, FECHA_HORA, ESTADO)
VALUES (CITAS_SEQ.NEXTVAL, 'Rocky', 'Perro', 'Maria Lopez', '+56912345678', 'Consulta general', 'Dr. Ramirez', '2026-04-01 10:00', 'Programada');

INSERT INTO CITAS (ID, NOMBRE_MASCOTA, TIPO_MASCOTA, NOMBRE_DUENO, TELEFONO_DUENO, SERVICIO, VETERINARIO, FECHA_HORA, ESTADO)
VALUES (CITAS_SEQ.NEXTVAL, 'Michi', 'Gato', 'Carlos Diaz', '+56923456789', 'Vacunacion', 'Dra. Soto', '2026-04-01 11:30', 'Programada');

INSERT INTO CITAS (ID, NOMBRE_MASCOTA, TIPO_MASCOTA, NOMBRE_DUENO, TELEFONO_DUENO, SERVICIO, VETERINARIO, FECHA_HORA, ESTADO)
VALUES (CITAS_SEQ.NEXTVAL, 'Luna', 'Perro', 'Ana Torres', '+56934567890', 'Cirugia menor', 'Dr. Ramirez', '2026-03-28 09:00', 'Completada');

INSERT INTO CITAS (ID, NOMBRE_MASCOTA, TIPO_MASCOTA, NOMBRE_DUENO, TELEFONO_DUENO, SERVICIO, VETERINARIO, FECHA_HORA, ESTADO)
VALUES (CITAS_SEQ.NEXTVAL, 'Simba', 'Gato', 'Pedro Sanchez', '+56945678901', 'Desparasitacion', 'Dra. Munoz', '2026-04-02 15:00', 'Programada');

INSERT INTO CITAS (ID, NOMBRE_MASCOTA, TIPO_MASCOTA, NOMBRE_DUENO, TELEFONO_DUENO, SERVICIO, VETERINARIO, FECHA_HORA, ESTADO)
VALUES (CITAS_SEQ.NEXTVAL, 'Thor', 'Perro', 'Sofia Herrera', '+56978901234', 'Vacunacion', 'Dra. Munoz', '2026-03-30 16:00', 'Cancelada');

COMMIT;
