-- Datos iniciales para la tabla PEDIDOS
-- Al menos 3 registros requeridos por las instrucciones

INSERT INTO PEDIDOS (ID, NOMBRE_PRODUCTO, CATEGORIA_PRODUCTO, CANTIDAD, PRECIO_UNITARIO, PRECIO_TOTAL, ESTADO, NOMBRE_CLIENTE, FECHA_PEDIDO)
VALUES (PEDIDOS_SEQ.NEXTVAL, 'Alimento Premium Perro 15kg', 'Alimento', 2, 25990.00, 51980.00, 'Pendiente', 'Maria Lopez', '2026-03-20');

INSERT INTO PEDIDOS (ID, NOMBRE_PRODUCTO, CATEGORIA_PRODUCTO, CANTIDAD, PRECIO_UNITARIO, PRECIO_TOTAL, ESTADO, NOMBRE_CLIENTE, FECHA_PEDIDO)
VALUES (PEDIDOS_SEQ.NEXTVAL, 'Arena Sanitaria Gato 10kg', 'Higiene', 3, 8990.00, 26970.00, 'Enviado', 'Carlos Diaz', '2026-03-18');

INSERT INTO PEDIDOS (ID, NOMBRE_PRODUCTO, CATEGORIA_PRODUCTO, CANTIDAD, PRECIO_UNITARIO, PRECIO_TOTAL, ESTADO, NOMBRE_CLIENTE, FECHA_PEDIDO)
VALUES (PEDIDOS_SEQ.NEXTVAL, 'Collar Antipulgas Perro', 'Salud', 1, 12990.00, 12990.00, 'Entregado', 'Ana Torres', '2026-03-15');

INSERT INTO PEDIDOS (ID, NOMBRE_PRODUCTO, CATEGORIA_PRODUCTO, CANTIDAD, PRECIO_UNITARIO, PRECIO_TOTAL, ESTADO, NOMBRE_CLIENTE, FECHA_PEDIDO)
VALUES (PEDIDOS_SEQ.NEXTVAL, 'Juguete Mordedor Resistente', 'Juguete', 4, 5990.00, 23960.00, 'Pendiente', 'Pedro Sanchez', '2026-03-22');

INSERT INTO PEDIDOS (ID, NOMBRE_PRODUCTO, CATEGORIA_PRODUCTO, CANTIDAD, PRECIO_UNITARIO, PRECIO_TOTAL, ESTADO, NOMBRE_CLIENTE, FECHA_PEDIDO)
VALUES (PEDIDOS_SEQ.NEXTVAL, 'Cama Ortopedica Perro Grande', 'Accesorios', 1, 34990.00, 34990.00, 'Entregado', 'Jorge Martinez', '2026-03-10');

COMMIT;
